### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by rgbkrk** [cloudpipe/cloudpickle#10]
Seems like this was started in depth [upstream within pyspark](https://github.com/apache/spark/pull/5173/files#diff-19fd865e0dd0d7e6b04b3b1e047dcda7L40), but we should bring it over.

**Comment by ogrisel** [comment]
Yes, I saw that this morning!

**Comment by sdegryze** [comment]
I will bring it over from pyspark and add Python 3.x to Travis this morning

**Comment by rgbkrk** [comment]
I'm wondering now if we should bring in the entire commit history for cloudpickle within pyspark. It's not too terrible to do, and I can merge it in with the commits we're making in the tests.

**Comment by rgbkrk** [comment]
Closed by #23.
