### ISSUE TITLE
cell_count is sometimes a list?

### ISSUE THREAD

**Issue by mrocklin** [cloudpipe/cloudpickle#100]
I'm getting the following error within the dask/distributed test suite on newer versions of cloudpickle.  Sorry for the lack of a clean reproducible test case.  This only appears to happen in odd situations.  Hopefully the error message is somewhat informative.

```
>   if cell_count >= 0 else
    None
        )
E       TypeError: '>=' not supported between instances of 'list' and 'int'
```

cc @llllllllll

**Comment by llllllllll** [comment]
Interesting, I'll look into this tonight or tomorrow morning. Does the dask test suite always trigger this?

**Comment by mrocklin** [comment]
Yes, dask/distributed.  Something like the following might work well:

    git clone git@github.com:dask/distributed.git
    cd distributed
    pip install -e .
    py.test distributed/cli/tests/test_dask_scheduler::test_preload_file

**Comment by llllllllll** [comment]
I am having trouble reproducing this issue:
```
(dask) [joe@jevnik distributed]$ py.test distributed/cli/tests/test_dask_scheduler.py::test_preload_file
=================================== test session starts ===================================
platform linux -- Python 3.6.1, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /home/joe/projects/python/distributed, inifile:
collected 14 items 

distributed/cli/tests/test_dask_scheduler.py .

================================ 1 passed in 1.39 seconds =================================
(dask) [joe@jevnik distributed]$ pip freeze | grep cloudpickle
cloudpickle==0.3.1
```

Is it possible that you are unpickling cached pickle'd objects created with cloudpickle 0.3.0?

**Comment by llllllllll** [comment]
I can reproduce this by using cloudpickle>=3 to deserialize an object created with cloudpickle<3. I think it should be easy to support this for cloudpickle 0.3.2 if people want that kind of compatibility.

**Comment by mrocklin** [comment]
> Is it possible that you are unpickling cached pickle'd objects created with cloudpickle 0.3.0?

That is possible.  I'll let you know if I reproduce this in the future.  Closing for now.

**Comment by mrocklin** [comment]
> I can reproduce this by using cloudpickle>=3 to deserialize an object created with cloudpickle<3. I think it should be easy to support this for cloudpickle 0.3.2 if people want that kind of compatibility.

I personally don't think that we should bother with cross-version cloudpickle compatibility.  There are almost certainly better uses of time.

**Comment by llllllllll** [comment]
One reason for supporting this would make it easier to ship individual components of systems which use cloudpickle to communicate. With this hard break all components must switch to 0.3.x at the same time. I can investigate a fix tonight but I won't spend too much time on it.
