### ISSUE TITLE
The imp package is pending deprecation in favor of importlib

### ISSUE THREAD

**Issue by jfinkels** [cloudpipe/cloudpickle#109]
According to the Python documentation for the [`imp`][1] package, "Deprecated since version 3.4: The imp package is pending deprecation in favor of importlib."

`cloudpickle.py` uses `imp.new_module()` (https://github.com/cloudpipe/cloudpickle/blob/master/cloudpickle/cloudpickle.py#L925) and `imp.find_module()` (https://github.com/cloudpipe/cloudpickle/blob/master/cloudpickle/cloudpickle.py#L1075), each of which has an equivalent function in `importlib`.

[1]: https://docs.python.org/3.7/library/imp.html

**Comment by rgbkrk** [comment]
How should we handle both Python2 and Python3? The python2 implementation is missing some of the functions used here -- https://docs.python.org/2/library/importlib.html

**Comment by jfinkels** [comment]
Unfortunately I'm not very familiar with importlib so I probably can't help you much here. :(

**Comment by pierreglaser** [comment]
In current master, we now use `imp` only in `Python 2` dedicated code blocks.
