### ISSUE TITLE
Making cloudpickle produce "consistent/deterministic" results.

### ISSUE THREAD

**Issue by robertnishihara** [cloudpipe/cloudpickle#120]
This question arose in the following context. I have multiple Python processes, and some classes are defined in each process. Sometimes class definitions are shipped from one process to another (using cloudpickle). Sometimes classes may be shipped multiple times or in multiple ways to a given process, and I'd like to deduplicate them based on the output of cloudpickle (that is, if `cloudpickle.dumps(class1) == cloudpickle.dumps(class2)`, then the classes are the "same" and I can throw away one of them. This works, but there are way too many false negatives (that is, two classes really are the same (in some sense), but `cloudpickle.dumps` gives different results on the two classes.

Here's one example that sort of illustrates the issue (although there are a number of ways this kind of thing can arise).

Suppose I do the following.

```python
import cloudpickle

class Foo1(object):
    def __init__(self):
        pass

serialized1 = cloudpickle.dumps(Foo1)
Foo2 = cloudpickle.loads(serialized1)
serialized2 = cloudpickle.dumps(Foo2)

assert serialized1 == serialized2  # This assertion fails.
```

I'd love for this kind of assertion to succeed. **Does anyone know if this is achievable or what the main obstacles are?**

Interestingly, if I iterate this a third time,

```python
Foo3 = cloudpickle.loads(serialized2)
serialized3 = cloudpickle.dumps(Foo3)

assert serialized2 == serialized3  # This succeeds.
```

then the assert succeeds, so maybe it suffices to use `cloudpickle.dumps(cloudpickle.loads(cloudpickle.dumps(cls)))` to deduplicate classes (though this seems kind of insane, and I haven't tested this extensively). **Would you expect this to work?**

One thing that may be related/revealing is the outputs I get if I do something similar in an IPython interpreter (instead of a regular Python interpreter). 

First copy and paste this block into IPython.

```python
import cloudpickle

class Foo(object):
    def __init__(self):
        pass

serialized1 = cloudpickle.dumps(Foo)
```

Then copy and paste this block into IPython.

```python
class Foo(object):
    def __init__(self):
        pass

serialized2 = cloudpickle.dumps(Foo)
```

Comparing `serialized1` and `serialized2` next to each other, they are

```
serialized1  # b'\x80\x02ccloudpickle.cloudpickle\n_rehydrate_skeleton_class\nq\x00(ccloudpickle.cloudpickle\n_builtin_type\nq\x01X\t\x00\x00\x00ClassTypeq\x02\x85q\x03Rq\x04X\x03\x00\x00\x00Fooq\x05c__builtin__\nobject\nq\x06\x85q\x07}q\x08X\x07\x00\x00\x00__doc__q\tNs\x87q\nRq\x0b}q\x0c(X\n\x00\x00\x00__module__q\rX\x08\x00\x00\x00__main__q\x0eX\x08\x00\x00\x00__init__q\x0fccloudpickle.cloudpickle\n_fill_function\nq\x10(ccloudpickle.cloudpickle\n_make_skel_func\nq\x11h\x01X\x08\x00\x00\x00CodeTypeq\x12\x85q\x13Rq\x14(K\x01K\x00K\x01K\x01KCc_codecs\nencode\nq\x15X\x04\x00\x00\x00d\x00S\x00q\x16X\x06\x00\x00\x00latin1q\x17\x86q\x18Rq\x19N\x85q\x1a)X\x04\x00\x00\x00selfq\x1b\x85q\x1cX\x1e\x00\x00\x00<ipython-input-1-d9b5c81388ae>q\x1dh\x0fK\x04h\x15X\x02\x00\x00\x00\x00\x01q\x1eh\x17\x86q\x1fRq ))tq!Rq"J\xff\xff\xff\xff}q#\x87q$Rq%}q&N}q\'NtRutR.'
serialized2  # b'\x80\x02ccloudpickle.cloudpickle\n_rehydrate_skeleton_class\nq\x00(ccloudpickle.cloudpickle\n_builtin_type\nq\x01X\t\x00\x00\x00ClassTypeq\x02\x85q\x03Rq\x04X\x03\x00\x00\x00Fooq\x05c__builtin__\nobject\nq\x06\x85q\x07}q\x08X\x07\x00\x00\x00__doc__q\tNs\x87q\nRq\x0b}q\x0c(X\n\x00\x00\x00__module__q\rX\x08\x00\x00\x00__main__q\x0eX\x08\x00\x00\x00__init__q\x0fccloudpickle.cloudpickle\n_fill_function\nq\x10(ccloudpickle.cloudpickle\n_make_skel_func\nq\x11h\x01X\x08\x00\x00\x00CodeTypeq\x12\x85q\x13Rq\x14(K\x01K\x00K\x01K\x01KCc_codecs\nencode\nq\x15X\x04\x00\x00\x00d\x00S\x00q\x16X\x06\x00\x00\x00latin1q\x17\x86q\x18Rq\x19N\x85q\x1a)X\x04\x00\x00\x00selfq\x1b\x85q\x1cX\x1e\x00\x00\x00<ipython-input-2-a08e1f07615d>q\x1dh\x0fK\x02h\x15X\x02\x00\x00\x00\x00\x01q\x1eh\x17\x86q\x1fRq ))tq!Rq"J\xff\xff\xff\xff}q#\x87q$Rq%}q&N}q\'NtRutR.'
```

They seem to be the same everywhere except that the first includes the string `<ipython-input-1-d9b5c81388ae>q\x1dh\x0fK\x04h` and the second includes the string `<ipython-input-2-a08e1f07615d>q\x1dh\x0fK\x02h`. **Any idea where these strings come from or if it is possible to remove them?**

cc @Wapaul1 @mehrdadn

**Comment by mehrdadn** [comment]
More revealing input: this class also fails the identity test as mentioned above:

	class Foo1(object):
		def ff(self): pass

but this doesn't:

	class Foo1(object):
		def f(self): pass

**Comment by mehrdadn** [comment]
My guess would've been that it just depends on the order in which the class's members are iterated through (hashtable order?) but it's not _quite_ consistent with what I see... there might be multiple sources of randomness.

**Comment by ssanderson** [comment]
The `<ipython-input-1-d9b5c81388ae>` strings are coming from the `co_filename` field of the pickled method's `__code__`:

```
In [1]: def foo():
   ...:     pass
   ...:

In [2]: foo.__code__.co_filename
Out[2]: '<ipython-input-1-5643a48472c0>'
```

The ultimate source of that string is the code in IPython that actually compiles your inputs; IPython generates a uuid to serve as the filename for each executed cell.

**Comment by robertnishihara** [comment]
Thanks, that's interesting! That explains the difference between Python and IPython. Sounds like that part may be unrelated to the other aspect of the question.

**Comment by mehrdadn** [comment]
It seems the problem is at least partially due to string "uniquification". When you `dump` once, the name of the method is only emitted once. But when you chain a second round of `dump`/`load`, the name of the method is emitted twice by the second `dump` -- once for the `FunctionType`, once for the `CodeType`. Not sure at the moment where exactly the inconsistency is occurring yet though.

**Comment by mehrdadn** [comment]
It turns out this isn't class-specific either. Another test case:

	def test1():
		def test2(): pass
		return test2

	def main(program, *args):
		T = test1
		t = cloudpickle.dumps(T)
		U = cloudpickle.loads(t)
		Tc = T.__code__
		Uc = U.__code__
		print((id(Tc.co_varnames[0]), id(Tc.co_consts[1].co_name)))  # identical
		print((id(Uc.co_varnames[0]), id(Uc.co_consts[1].co_name)))  # not identical
		assert t == cloudpickle.dumps(U)

**Comment by mehrdadn** [comment]
Okay, I think I may have found the (or a?) problem? The issue is that `type.CodeType(...)` sometimes copies the strings in the `co_varnames` argument (most likely in order to intern them). This changes the identity of the string, resulting in a different pickle output the next time. I'm not sure what the best solution is, but pickling twice may indeed be a viable temporary hack...

**Comment by adamklein** [comment]
I really, really would like this behavior. I'm using cloudpickle to (try to) produce a deterministic token for lambdas and functions, and prefer not to give it up. For instance, given this test rig:

```
import cloudpickle as cp

import numpy as np
import pandas as pd
import dask.base as db


def something_random(df):
    lg = np.log(df)
    rm = pd.rolling_mean(lg, 10)
    return rm


def run():
    print(cp.dumps(something_random))
    print(db.tokenize(cp.dumps(something_random)))


if __name__ == "__main__":
    run()
```

I get one of two outputs in an individual Python process:

```
b'\x80\x02ccloudpickle.cloudpickle\n_fill_function\nq\x00(ccloudpickle.cloudpickle\n_make_skel_func\nq\x01ccloudpickle.cloudpickle\n_builtin_type\nq\x02X\x08\x00\x00\x00CodeTypeq\x03\x85q\x04Rq\x05(K\x01K\x00K\x03K\x03KCc_codecs\nencode\nq\x06X\'\x00\x00\x00t\x00\x00j\x01\x00|\x00\x00\xc2\x83\x01\x00}\x01\x00t\x02\x00j\x03\x00|\x01\x00d\x01\x00\xc2\x83\x02\x00}\x02\x00|\x02\x00Sq\x07X\x06\x00\x00\x00latin1q\x08\x86q\tRq\nNK\n\x86q\x0b(X\x02\x00\x00\x00npq\x0cX\x03\x00\x00\x00logq\rX\x02\x00\x00\x00pdq\x0eX\x0c\x00\x00\x00rolling_meanq\x0ftq\x10X\x02\x00\x00\x00dfq\x11X\x02\x00\x00\x00lgq\x12X\x02\x00\x00\x00rmq\x13\x87q\x14X\x15\x00\x00\x00private/ak_hashing.pyq\x15X\x10\x00\x00\x00something_randomq\x16K\x08h\x06X\x06\x00\x00\x00\x00\x01\x0f\x01\x12\x01q\x17h\x08\x86q\x18Rq\x19))tq\x1aRq\x1bJ\xff\xff\xff\xff}q\x1c\x87q\x1dRq\x1e}q\x1f(h\x0eccloudpickle.cloudpickle\nsubimport\nq X\x06\x00\x00\x00pandasq!\x85q"Rq#h\x0ch X\x05\x00\x00\x00numpyq$\x85q%Rq&uN}q\'NtR.'
1fd5884366d1aafeffaa21eb290b6e63 
```
```
b'\x80\x02ccloudpickle.cloudpickle\n_fill_function\nq\x00(ccloudpickle.cloudpickle\n_make_skel_func\nq\x01ccloudpickle.cloudpickle\n_builtin_type\nq\x02X\x08\x00\x00\x00CodeTypeq\x03\x85q\x04Rq\x05(K\x01K\x00K\x03K\x03KCc_codecs\nencode\nq\x06X\'\x00\x00\x00t\x00\x00j\x01\x00|\x00\x00\xc2\x83\x01\x00}\x01\x00t\x02\x00j\x03\x00|\x01\x00d\x01\x00\xc2\x83\x02\x00}\x02\x00|\x02\x00Sq\x07X\x06\x00\x00\x00latin1q\x08\x86q\tRq\nNK\n\x86q\x0b(X\x02\x00\x00\x00npq\x0cX\x03\x00\x00\x00logq\rX\x02\x00\x00\x00pdq\x0eX\x0c\x00\x00\x00rolling_meanq\x0ftq\x10X\x02\x00\x00\x00dfq\x11X\x02\x00\x00\x00lgq\x12X\x02\x00\x00\x00rmq\x13\x87q\x14X\x15\x00\x00\x00private/ak_hashing.pyq\x15X\x10\x00\x00\x00something_randomq\x16K\x08h\x06X\x06\x00\x00\x00\x00\x01\x0f\x01\x12\x01q\x17h\x08\x86q\x18Rq\x19))tq\x1aRq\x1bJ\xff\xff\xff\xff}q\x1c\x87q\x1dRq\x1e}q\x1f(h\x0cccloudpickle.cloudpickle\nsubimport\nq X\x05\x00\x00\x00numpyq!\x85q"Rq#h\x0eh X\x06\x00\x00\x00pandasq$\x85q%Rq&uN}q\'NtR.'
5d41ac5833887333eb991032230322ce
```

You can see the numpy and pandas imports are reversed. I believe this has to do with iterating through sets especially, which is known in python < 3.6 to be non-deterministic (I'm using python 3.5.4)

I haven't figured out exactly where this is occurring in the library, and I'm not sure I actually observed this is 0.3.x, but definitely started noticing in 0.4.0 of cloudpickle.

cc @mrocklin @pitrou

**Comment by mrocklin** [comment]
My guess is that full determinism in cloudpickle would be challenging to do comprehensively, but that special cases might be improved on a case by case basis.

> You can see the numpy and pandas imports are reversed. I believe this has to do with iterating through sets especially, which is known in python < 3.6 to be non-deterministic (I'm using python 3.5.4)

This is a good example because it seems pretty simple in this context, but as @ogrisel points out can be challenging in general.

> Is the official pickle guaranteed to provide a deterministic pickle behavior in general? For instance of large dicts under Python < 3.6 that would mean sorting the keys which would be expensive.

My guess is that when choosing between partially improved determinism and performance that cloudpickle should choose performance.

**Comment by pitrou** [comment]
> My guess is that when choosing between partially improved determinism and performance that cloudpickle should choose performance.

Ditto. It would be nice to have both at the same time but I'm not sure how workable that is.

In any case, I think the onus is on the persons trying to push for determinism to devise a working prototype and then measure its performance.

**Comment by pitrou** [comment]
Also, on Python 3.6 dicts became ordered by default, but it's an implementation detail rather than a guaranteed. And the ordering for sets is still unspecified.

**Comment by adamklein** [comment]
I agree w/you on performance over determinism, because it's simple enough for me to rely on something other than the cloudpickle byte string for a token; I was just curious if I might get it "for free".

**Comment by emlynoregan** [comment]
I'm using cloudpickle 0.3.1, and python 2.7.13, and when I run the OP's code, the assertion succeeds; I can't find an example where the serialisation isn't deterministic. Is that what other people are seeing?

**Comment by emlynoregan** [comment]
Here it is passing the assertion on python 3.6.1 and v0.2.2 of cloudpickle:

https://repl.it/repls/AlarmingHuskyBoar

**Comment by emlynoregan** [comment]
I've just run a script to test this across versions of the cloudpickle package from pypi. Here's the result:

python version: (3, 5, 3, 'final', 0)
*****************************************
cloudpickle version: 0.5.2
ASSERTION FAILED serialisations don't match
*****************************************
cloudpickle version: 0.5.1
assertion passed
*****************************************
cloudpickle version: 0.4.1
assertion passed
*****************************************
cloudpickle version: 0.4.0
ASSERTION FAILED serialisations don't match
*****************************************
cloudpickle version: 0.3.1
assertion passed
*****************************************
cloudpickle version: 0.2.2
assertion passed
*****************************************
cloudpickle version: 0.2.1
assertion passed
*****************************************
cloudpickle version: 0.1.1
assertion passed
*****************************************
cloudpickle version: 0.1.0
ASSERTION FAILED module 'cloudpickle' has no attribute 'loads'

scripts are here:
https://github.com/emlynoregan/serfail

**Comment by adamklein** [comment]
@emlynoregan from my investigations, here is where things are non-deterministic:

1) In `extract_code_globals` , `out_names` should be ordered
2) In `extract_func_data`, the following need to be ordered: `f_globals`, `dct`, and `base_globals`

After correcting for those, I haven't seen non-determinism.

**Comment by pitrou** [comment]
Things can be non-deterministic anywhere you have a non-ordered container (such as `dict`, `set`, etc.).

**Comment by adamklein** [comment]
Right, to @pitrou's point, I'm assuming whatever is closed over in the function is also ordered - otherwise you're in trouble :)
