### ISSUE TITLE
cloudpickle.dumps() uses protocol 2 by default

### ISSUE THREAD

**Issue by pitrou** [cloudpipe/cloudpickle#123]
I'm not sure why that is, but protocol 3 should be the default on Python 3 and can be significantly faster:
```
>>> b = b"x" * (1024**2)
>>> %timeit cloudpickle.dumps(b)
1.45 ms ± 5.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
>>> %timeit cloudpickle.dumps(b, protocol=3)
586 µs ± 2.67 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
Unpickling is also faster:
```
>>> d1 = cloudpickle.dumps(b)
>>> d2 = cloudpickle.dumps(b, protocol=3)
>>> %timeit pickle.loads(d1)
225 µs ± 843 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
>>> %timeit pickle.loads(d2)
67.1 µs ± 348 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by mrocklin** [comment]
I suspect that this is so that Python 3 pickled bytes can sometimes be unpickled on Python 2.  I'm not at all defending this decision, just posing a guess.

**Comment by mrocklin** [comment]
@pitrou , why not `HIGHEST_PROTOCOL`?

**Comment by pitrou** [comment]
Standard `pickle` uses `DEFAULT_PROTOCOL`, IMHO it's less confusing if we don't deviate from it. But no strong opinion either.

**Comment by ogrisel** [comment]
I think the main use case for cloudpickle is to allow interprocess communication between Python workers in a parallel computing system (PySpark, dask, joblib). pickled object will probably be not stored in the long term, just the time of sending a message to the next and we can reasonably expect that all the Python process communicating together in such a system to have the same version so `HIGHEST_PROTOCOL` should be fine in that context.

However, some users might already use it in another scenario where Python 2 / Python 3 communication is actually a use case.

**Comment by rgbkrk** [comment]
> Pickled objects will probably not be stored in the long term, just the time of sending a message to the next and we can reasonably expect that all the Python processes communicating together in such a system will have the same version so using `HIGHEST_PROTOCOL` should be fine in that context.

Totally in agreement with this. I think we should switch to `HIGHEST_PROTOCOL` by default. For the users I support, their primary use is on Spark. I'd prefer the performance over potential Python process interop. As long as the drivers and the executors match, I think we're ok.

@rdblue -- when people run our Python3 kernel with Spark, does the executor match the driver?

**Comment by HyukjinKwon** [comment]
Hi all, I happen to come here while reading the recent interesting issues and changes.

Here are Spark related JIRA and PR, https://issues.apache.org/jira/browse/SPARK-18161 and `https://github.com/apache/spark/pull/15670`. I hope this could be helpful.

**Comment by rdblue** [comment]
Yes, we always start executors with the same Spark build that was used for the driver.

**Comment by pitrou** [comment]
Fair enough. Let's use `HIGHEST_PROTOCOL` then :-)

**Comment by ogrisel** [comment]
See PR #127 to implement the switch.

**Comment by Peque** [comment]
#127 was merged, so closing this...
