### ISSUE TITLE
Pickling error with 0.5.1.

### ISSUE THREAD

**Issue by robertnishihara** [cloudpipe/cloudpickle#131]
The following works in 0.4.1 but breaks with 0.5.1. I've tried this with Python 3.6. I've also tried using protocols 0, 1, 2, 3, 4.

```python
import cloudpickle

class Foo(object):
    pass

def f():
    Foo

cloudpickle.dumps(f)
```

Then in a separate Python interpreter:

```python
>>> import cloudpickle
>>> cloudpickle.loads(...the string dumped above...)
AttributeError: Can't get attribute 'Foo' on <module '__main__'>
```

**Comment by iaroslav-ai** [comment]
Just encountered same bug. Will use 0.4.0 version of cloudpickle for now.

**Comment by ogrisel** [comment]
Sorry, this is extremely embarrassing. I wonder why this has not been caught by our test suite. I will investigate.

**Comment by ogrisel** [comment]
The problem is also there in 0.4.2 so was probably caused by the change to `_fill_function` arguments done in: #130.

**Comment by ogrisel** [comment]
Fixed in master.

**Comment by ogrisel** [comment]
FYI cloudpickle 0.5.2 whas released.
