### ISSUE TITLE
Released v0.4.3 after v0.5.2?

### ISSUE THREAD

**Issue by colinc719** [cloudpipe/cloudpickle#170]
Why was the most recent version released as v0.4.3 when v0.5.2 already exists?

@HyukjinKwon

**Comment by llllllllll** [comment]
I believe this was to backport a bugfix to 0.4 because there are incompatibilities between 0.5 and 0.4.

**Comment by colinc719** [comment]
I'd like to get this update https://github.com/cloudpipe/cloudpickle/commit/1105da108cbf839edcf89f8723f79f9d2eab9ad3 to fix.  Would it be possible to release a newer v0.5.x version which includes that (and other) updates?

**Comment by HyukjinKwon** [comment]
I released both 0.5.3 and 0.4.4. I am closing this.
