### ISSUE TITLE
cloudpickle could extend pickle5

### ISSUE THREAD

**Issue by pitrou** [cloudpipe/cloudpickle#179]
I'm not sure how adventurous people here want to get, but cloudpickle could extend [pickle5](https://pypi.org/project/pickle5/) instead of the built-in `pickle` module, at least when available.

@ogrisel

**Comment by jakirkham** [comment]
Sounds like a great idea to me. 👍

cc @mrocklin

**Comment by ogrisel** [comment]
+1 :)

**Comment by jakirkham** [comment]
I'm curious if anyone has tried this. Some of the discussion in PR ( https://github.com/cloudpipe/cloudpickle/pull/253 ) suggests it might have been explored. Also looks like PR ( https://github.com/cloudpipe/cloudpickle/pull/308 ) added the missing keyword argument.

**Comment by jakirkham** [comment]
Rough attempt of this in PR ( https://github.com/cloudpipe/cloudpickle/pull/364 ). Probably still needs a bit more work.

**Comment by jakirkham** [comment]
> Rough attempt of this in PR ( #364 ). Probably still needs a bit more work.

This has been replaced by PR ( https://github.com/cloudpipe/cloudpickle/pull/370 ). Could use some reviews if anyone has time to look 🙂

**Comment by jakirkham** [comment]
Thanks all! 😄

This is now included in 1.5.0 recently released.
