### ISSUE TITLE
Pickling Annotations can fail

### ISSUE THREAD

**Issue by cicdw** [cloudpipe/cloudpickle#193]
Now that [cloudpickle is including annotations](https://github.com/cloudpipe/cloudpickle/commit/6d03ffe1b06d5abc8f8615ac57d475946aca4b38), there are certain `typing` classes that fail to pickle in versions of python < 3.7 that are now raising errors when included as annotations:

```python
## python 3.6.6

import typing
import cloudpickle

tt = typing.Union[str, typing.List[str]]
cloudpickle.dumps(tt, protocol=cloudpickle.DEFAULT_PROTOCOL) # always fails
# _pickle.PicklingError: Can't pickle typing.Union[str, typing.List[str]]: it's not the same object as typing.Union

def f(x: tt) -> tt:
    return x

## passes in cloudpickle==0.5.3 because type annotations were ignored
## but fails in 0.5.4+
cloudpickle.dumps(f, protocol=cloudpickle.DEFAULT_PROTOCOL)
```

All of this works fine in python 3.7

Related: https://github.com/python/typing/issues/511

**Comment by ogrisel** [comment]
Can you please open a new issue?
