### ISSUE TITLE
Cannot pickle a python class

### ISSUE THREAD

**Issue by markbudiak** [cloudpipe/cloudpickle#194]
Hi,
I am using dask to help me distribute my computations. It seems that dask is using cloudpickle. Everytime I run it I get the following error:

```python-traceback
File "/home/ubuntu/anaconda3/envs/job_classification/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 1060, in _make_skel_func
    base_globals['\_\_builtins\_\_'] = \_\_builtins\_\_
TypeError: 'str' object does not support item assignment
```

How can I fix this issue?

**Comment by robertnishihara** [comment]
Can you post a minimal code example that reproduces the problem?

**Comment by ogrisel** [comment]
Which version of cloudpickle is this? This code has changed in cloudpickle 0.5.6. Maybe this has fixed your issue?

**Comment by suquark** [comment]
I met this problem before for using different versions of cloudpickle (forget to restart processes after updating cloudpickle).

**Comment by ogrisel** [comment]
We really need a minimal reproduction example that triggers the problem on a recent version of cloudpickle in order to fix it.

**Comment by markbudiak** [comment]
In the end, I found that it was not a pickle issue but dask related issue. Thanks for comments. Closing this.
