### ISSUE TITLE
Add a non-regression test to ensure that we do not include un-necessary global variables in the pickles

### ISSUE THREAD

**Issue by ogrisel** [cloudpipe/cloudpickle#203]
Basically at least one of the following to checks should be refactored into a test part of the cloudpickle test suite:

- https://github.com/cloudpipe/cloudpickle/issues/202#issuecomment-421364343
- https://github.com/cloudpipe/cloudpickle/issues/202#issuecomment-421366065

**Comment by ogrisel** [comment]
@pierreglaser if you ever feel bored, don't hesitate to take this one ;)

**Comment by pierreglaser** [comment]
will do ;)
