### ISSUE TITLE
cloudpickle failing to load python2 object under python3

### ISSUE THREAD

**Issue by ericksc** [cloudpipe/cloudpickle#213]
Under Python3,
I tried to load a pickled object on Python2,
but it is failing at function: def _builtin_type(name)

`pkl = cloudpickle.load(f, fix_imports=True, encoding='bytes')`
    
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

`name = b'CodeType'`

    `def _builtin_type(name):`
`>       return getattr(types, name)`
`E       TypeError: getattr(): attribute name must be string`

**Comment by TheButlah** [comment]
The README.md explicitly disallows this:
> it is meant to send objects between processes running the same version of Python. It is discouraged to use cloudpickle for long-term storage.

**Comment by ogrisel** [comment]
As @TheButlah said, this use-case is outside of the scope of the project.

To allow for long term storage of objects / data I would really advise you to use a serialization format with an explicit application specific schema and serialization / de-serialization logic that does not depend on specific versions of Python or private implementation details of your Python classes or third party libraries.

To build such serialization layer I you can have a look at: protobuf, msgpack, avro or even JSON (preferably with a schema) or XML.

Closing this.
