### ISSUE TITLE
New features in cloudpickle give unexpected results

### ISSUE THREAD

**Issue by suquark** [cloudpipe/cloudpickle#214]
I am a developer of [Ray](https://github.com/ray-project/ray), and we have something we want to fix soon. We are updating cloudpickle to 0.6.1 to fix an [issue](https://github.com/ray-project/ray/issues/2685). However, although version 0.6.1 fixed our issue, it  [failed to pickle several objects correctly](https://github.com/ray-project/ray/pull/2928). These failures only happened when we were trying to run a complex set of unittests so we found it hard to give some simple instructions to trigger those cases. 

I investigated into those cases and created a [PR](https://github.com/ray-project/ray/pull/3076) which fixed those failures and this PR showed that:

* When restoring the global variables, in Ray we should always give serialized global variables higher priority (that is, always overriding existing global variables). The new changes in cloudpickle gives higher priority to existing global variables.
* In Ray, do not try to infer global variables from the `__module__` attribute of a function. The new changes in cloudpickle try to make use of `__module__` when it fails to fetch global variables.

It seems that these new features are not compatible with Ray, but they are not really bugs to be reverted. And since we would like to follow the cloudpickle upstream instead of maintaining our own copy, the proper way should be creating several switches to control the availability of those new features in the upstream. Could you have any suggestions about how and where should we put those switches?

**Comment by suquark** [comment]
@ogrisel Could anyone look into this issue? I feel sorry but we want to fix it soon.

**Comment by robertnishihara** [comment]
@suquark are there things that we can change on the Ray side to fix the problem? Also, do you know what the motivating issues for changing cloudpickle's behavior in these instances were?

**Comment by mitar** [comment]
@robertnishihara One option could be that Ray would allow one to provide its own version of serialization code. For example, for us this would then allow us to use plain pickle and side-step all these issues.

**Comment by rgbkrk** [comment]
I'm not able to look into the issue, nor do I have the necessary context for me to investigate.

**Comment by ogrisel** [comment]
@suquark I agree we could have switches for customizing this cloudpickle specific behavior.

I think such switches could be passed as arguments to the constructor of the `CloudPickler` class.

`override_existing_globals`

> In Ray, do not try to infer global variables from the __module__ attribute of a function. The new changes in cloudpickle try to make use of __module__ when it fails to fetch global variables.

I am not sure what you mean by this. Could you provide a small example outside of the context of Ray?

**Comment by ogrisel** [comment]
Additional question: do you want this for the functions / classes defined in the `__main__` module that reference global variables from that same module only or something more generic?

**Comment by suquark** [comment]
@ogrisel *infer global variables* refers to the following code:

https://github.com/cloudpipe/cloudpickle/blob/2ba0847b862f6ccf118a1b301e779890df3b6307/cloudpickle/cloudpickle.py#L643-L649

https://github.com/cloudpipe/cloudpickle/blob/2ba0847b862f6ccf118a1b301e779890df3b6307/cloudpickle/cloudpickle.py#L1105-L1117

We found it could get a wrong reference of itself when serializing a recursive function under some complex settings. (We further hacked the recursive call by assign the function itself to its globals after deserialization.)

**Comment by ogrisel** [comment]
This should be fixed by #240.

**Comment by ogrisel** [comment]
The fix is now available in cloudpickle 0.8.0 on PyPI.
