### ISSUE TITLE
Inconsitent check when accessing __module__ attribute

### ISSUE THREAD

**Issue by pierreglaser** [cloudpipe/cloudpickle#217]
in `Cloudpickler.save_function_tuple`, 
the `__module__ ` attribute of the function being saved is accessed two times:
 * once in `Cloupickler.extract_func_data`  after this conditional statement:
```python
if hasattr(func, '__module__') and func.__module__ is not None
```
* then, further away in `save_function_tuple`, `func.__module__` is accessed without a previous `hasattr` condition.

This should be cleaned, removing the `hasattr` check in the first statement, or adding one the second time.

**Comment by ogrisel** [comment]
If you remove it in the first, does that make some tests fail?
