### ISSUE TITLE
CI configuration to run the tests of Ray against development version of cloudpickle

### ISSUE THREAD

**Issue by ogrisel** [cloudpipe/cloudpickle#238]
In the recently merged #236, @pierreglaser added the ability to launch the tests of some downstream projects (loky, joblib and dask/distributed) in order to be able to detect if a specific PR is likely to introduce a regression in a downstream project just by adding the `[ci downstream]` flag in a commit message of the last commit of the PR.

It would be great to add the build configuration to launch the Ray test suite in a similar manner.

I also opened #237 to do the same for PySpark.

**Comment by ogrisel** [comment]
@suquark @robertnishihara would any of you be interested in helping with this?

**Comment by robertnishihara** [comment]
Thanks @ogrisel, we'll submit a patch :)
