### ISSUE TITLE
python 3.8 breaks cloudpickle namedtuple saving

### ISSUE THREAD

**Issue by pierreglaser** [cloudpipe/cloudpickle#250]
```python
import collections
import cloudpickle


MyTuple = collections.namedtuple('MyTuple', ['a', 'b', 'c'])
t = MyTuple(1, 2, 3)
cloudpickle.dumps(t)
```

fails with:

```python
TypeError: cannot pickle '_collections._tuplegetter' object      
```

on a recent version of python master:
`Python 3.8.0a1+ (heads/master:49fd6dd887, Feb 21 2019, 10:19:05)`

Reason:  optimization of `namedtuple` attribute access:
https://bugs.python.org/issue32492

**Comment by llllllllll** [comment]
Has the 3.8 feature freeze begun? It would be easier to serialize these objects if `_tuplegetter` exposed the index as a read-only getter like the doc. I can try to open a PR to expose that, or to just make the objects serializable directly in CPython.

**Comment by pierreglaser** [comment]
> Has the 3.8 feature freeze begun?

I don't think so. It is not urgent, I added it for the record.

>or to just make the objects serializable directly in CPython

Do you think cpython core devs will +1?

**Comment by llllllllll** [comment]
`_collections` is still optional, I think for pypy to use the same stdlib code, or cases where C extensions aren't desired. Right now this object is defined as:

```
try:
    from _collections import _tuplegetter
except ImportError:
    _tuplegetter = lambda index, doc: property(_itemgetter(index), doc=doc)
```

so in one case the object is serializable and in the other it is not. I am not sure they would go through the effort of adding this serialization themselves, but I hope they would accept a PR if it was contributed. We can link to this issue as an example of code that depended on being able to serialize the members. I am working on adding a test for `_tuplegetter.__reduce__` then I will open a PR for CPython.

**Comment by llllllllll** [comment]
Hmm, it appears that `property` isn't normally serializable, we just have special support for property. I will still open the PR but it I am less confident it will be accepted now.

**Comment by llllllllll** [comment]
https://bugs.python.org/issue36068

**Comment by llllllllll** [comment]
CPython accepted the PR!

**Comment by pierreglaser** [comment]
That was fast ;) thanks a lot!

**Comment by pierreglaser** [comment]
Can confirm that with the current python master, `test_namedtuple` passes again!
