### ISSUE TITLE
Cut 1.0 release

### ISSUE THREAD

**Issue by mrocklin** [cloudpipe/cloudpickle#260]
Any objection to bumping the release to 1.0 next time around?  There are a variety of reasons to do this, but the best I've heard is that some institutions have a hard time justifying using software with a version number less than 1.0 to their IT administrative staff.

**Comment by ogrisel** [comment]
No objection but I would really appreciate it if we could decide whether to merge this first:

https://github.com/cloudpipe/cloudpickle/pull/246 (support isinstance and enums)

**Comment by ogrisel** [comment]
Let's cut the 1.0 release prior to merging #246 and maybe consider merging for a subsequent 1.1.0 release.

**Comment by ogrisel** [comment]
I just released 1.0.0.

**Comment by mrocklin** [comment]
Woot.  Thanks @ogrisel
