### ISSUE TITLE
Security compared to the standard pickle

### ISSUE THREAD

**Issue by dumblob** [cloudpipe/cloudpickle#283]
The standard Python pickle is highly insecure (mainly due to its nature). Does `cloudpickle` handle security in a better way? What are the differences from the security point of view?

**Comment by moreati** [comment]
`cloudpickle` is the same. Just as with `pickle`, unpickling an arbitrary value with cloupickle can execute arbitrary code, e.g.

```python
>>> print(open('echo-hello-world.proto0.pkl', encoding='ascii').read())
cos
system
(S'echo hello world'
tR.
>>>
>>> import os
>>> import pickle
>>> pickle.load(open('echo-hello-world.proto0.pkl', 'rb'))
hello world
0
>>>
>>> import cloudpickle
>>> cloudpickle.__version__
'1.2.0'
>>> cloudpickle.load(open('echo-hello-world.proto0.pkl', 'rb'))
hello world
0
```

**Comment by dumblob** [comment]
Ok, thanks, that precisely answers my question. Btw if you would know of a secure "auto serialization" solution, please let me know (I found some schema-full pickle variants, but they were constrained and needed upfront schema definition :cry:).

**Comment by moreati** [comment]
I don't. The problem itself is ill-defined. It means different things to different people. It may not have a solution.

My ongoing research/experimentation is https://github.com/moreati/pickle-fuzz. The closest I can offer is https://github.com/moreati/pikl, but _it is not ready_.
