### ISSUE TITLE
[RFC] make @pierreglaser a maintainer of cloudpickle

### ISSUE THREAD

**Issue by ogrisel** [cloudpipe/cloudpickle#287]
Hi all,

@pierreglaser has contributed numerous deep improvements to cloudpickle over the past year including a new implementation of the CloudPickler class in #253 to derive from the fast C implementation of `pickle.Pickler` in Python 3.8+ instead of the significantly slower Python implementation (along the related supporting changes in the CPython standard library python/cpython#12499 python/cpython#12588 ).

As a result Pierre is now the most familiar with the internal details of the cloudpickle code base so it would make sense to grant him the maintainers right on the github repo and on pypi.org.

Pinging current members with maintainers' rights: @rgbkrk @holdenk @HyukjinKwon @jakirkham @llllllllll @mrocklin @pitrou @ssanderson.

BTW if anyone has any comments on how we should improve the maintenance of this project please feel free to comment on this thread.

**Comment by pitrou** [comment]
> As a result Pierre is now the most familiar with the internal details of the cloudpickle code base so it would make sense to grant him the maintainers right on the github repo and on pypi.org.

+1

**Comment by ogrisel** [comment]
Invite sent. Welcome to the team @pierreglaser!

**Comment by jakirkham** [comment]
Thanks @ogrisel. Welcome @pierreglaser! 😃
