### ISSUE TITLE
1.2.2 sdist missing from PyPI

### ISSUE THREAD

**Issue by koobs** [cloudpipe/cloudpickle#296]
The source distribution for 1.2.2 is missing from PyPI. We (FreeBSD), and I imagine other downstream packagers, use the sdist to produce packages as a canonical/primary source.

**Comment by ogrisel** [comment]
1.2.2 is not released yet. The last tag on github is 1.2.1: https://github.com/cloudpipe/cloudpickle/tree/v1.2.1

**Comment by jakirkham** [comment]
Looks like this was since added to PyPI. Though we don't seem to have git tag on GitHub. Would someone be able to push that?

**Comment by pierreglaser** [comment]
@jakirkham sorry about that. Just pushed the `1.2.2` tag.

**Comment by jakirkham** [comment]
No worries. Thanks for doing that @pierreglaser !😀
