### ISSUE TITLE
Test failures with py2.7 on Gentoo

### ISSUE THREAD

**Issue by mgorny** [cloudpipe/cloudpickle#297]
Complete log: [dev-python:cloudpickle-1.2.1:20190629-071637.log](https://github.com/cloudpipe/cloudpickle/files/3341591/dev-python.cloudpickle-1.2.1.20190629-071637.log)

FWICS, all the test failures boil down to:

```
    def example():
>       x = xml.etree.ElementTree.Comment # potential AttributeError
E       AttributeError: 'module' object has no attribute 'etree'
```

But importing the module directly from `python2.7` works.

**Comment by ogrisel** [comment]
Indeed I can reproduce with a [docker image of gentoo](https://github.com/gentoo/gentoo-docker-images) with Python 2.7.15. However this issue does not impact Python 3.6 on the docker image so I am tempted to leave that issue as low priority until we drop Python 2 support in cloudpickle next year or so ;)

If someone is interested in submitting a PR in the mean time, please feel free to do so.

**Comment by ogrisel** [comment]
python 2 is no longer supported.
