### ISSUE TITLE
pickling NewType raises an error

### ISSUE THREAD

**Issue by djarecka** [cloudpipe/cloudpickle#301]
I'm trying to pickle a custom-designed type, that uses `typing.NewType`, and I'm getting an error:
```
Can't pickle local object 'NewType.<locals>.new_type'
```

The easiest way to reproduce the error:
```
import cloudpickle as cp
import typing as ty

my_list=ty.NewType("my_list", ty.List)
cp.dumps(my_list)
```

I'm testing on OSX, python 3.7.3 and cloudpickle 1.2.1., but see the same error testing on travis with Linux.

**Comment by pierreglaser** [comment]
I did not try on OSX, but I cannot reproduce on Linux:
```
Package          Version
---------------- -------
backcall         0.1.0  
cloudpickle      1.2.1  
decorator        4.4.0  
ipython          7.7.0  
ipython-genutils 0.2.0  
jedi             0.14.1 
parso            0.5.1  
pexpect          4.7.0  
pickleshare      0.7.5  
pip              19.0.3 
prompt-toolkit   2.0.9  
ptyprocess       0.6.0  
Pygments         2.4.2  
setuptools       40.8.0 
six              1.12.0 
traitlets        4.3.2  
wcwidth          0.1.7  
```

```
Python 3.7.3 (tags/v3.7.3:ef4ec6ed12, Jul 29 2019, 10:41:07) 
```

**Comment by djarecka** [comment]
@pierreglaser - thank you for your answer! I've been trying to reproduce this error today myself, and I realized that I messed up pickling libraries and imports. We were using `cloudpickle` and `pickle` in the project, and the error was actually coming from the `pickle` library... Sorry for this!
