### ISSUE TITLE
_is_dynamic fails on submodule in .so file

### ISSUE THREAD

**Issue by henryiii** [cloudpipe/cloudpickle#354]
When `_is_dynamic` checks a module, it only looks for the `__spec__` and `__file__` of the module being checked, and if that is not defined, it looks for the `__path__` on the module above. For a PyBind11 module with a submodule, the `__file__` is defined on the main module, but not submodules, and there is no `__path__`. So things in submodules cannot be cloudpickled.

I think the function should be recursively checking up the the module path, and shouldn't try to access `parent.__path__` without a check or try.

**Comment by henryiii** [comment]
Ref: https://github.com/scikit-hep/boost-histogram/issues/342

**Comment by henryiii** [comment]
(It might be that PyBind11 should set `__file__` on submodules)

**Comment by pierreglaser** [comment]
Thanks for reporting. I'll work on a fix ASAP. If you know of a good way to fix this, feel free to submit a PR. I'm not an expert of the Python import machinery.

**Comment by henryiii** [comment]
I don't want to break dynamic modules. Can a dynamic module be nested inside a normal one? If not, this is an easy fix. And what's an example of a dynamic module?

**Comment by pierreglaser** [comment]
We have tests that should cover the pickling of dynamic modules, so if your fix breaks the picking of dynamic module, the CI will let us know. I’m not quite sure what you mean by “nested dynamic modules”. Feel free to add any unit test that you think is relevant alongside your fix :)

**Comment by pierreglaser** [comment]
> Nevermind, setting this in C++ causes a segfault.

Out of curiosity, are you using the C/Python API to do such an operation?

**Comment by henryiii** [comment]
Yes; the PyBind11 API which is just a wrapper around the CPython API. Not sure where the crash came from, `__file__` might not have been set yet.
