### ISSUE TITLE
Adding pickle.load and pickle.loads into cloudpickle namespace

### ISSUE THREAD

**Issue by parnmatt** [cloudpipe/cloudpickle#36]
I understand that you do not include an unpickler:
> [It does not include an unpickler, as standard python unpickling suffices.](https://github.com/cloudpipe/cloudpickle/blob/master/cloudpickle/cloudpickle.py#L9)

However it would be convenient if injecting the pickle `load()` and `loads()` methods into your name space, thus it can be used as a drop in.

You have `import pickle` surely it's almost a simple as:
```python
    load = pickle.load
    loads = pickle.loads
```

If I am honest, I am a little inconvenient to have to write:
```python
    try:
        import cPickle as pickle
    except ImportError:
        import pickle

    import cloudpickle
```
when I need to read and write pickled files/objects etc., and have to remember to use `cloudpickle.dump`[`s`]`()` and `pickle.load`[`s`]`()`.

Just having those functions in your namespace, just redirecting the work to `pickle` itself would make code cleaner, can therefore can be used as a drop in replacement:

```python
    import cloudpickle as pickle
```
This is common practise with an alternative pickler `dill`:
```python
    import dill as pickle
```
`dill` is great, but I have found that `cloudpickle` can pickle something I need that `dill` cannot.

I wouldn't mind even doing it myself if need be; however rather than doing the work (which may not be as simple as stated above), creating a pull request, and it being rejected because you do not want this feature; I thought I would ask first.

Is this something that you would be interested in doing yourselves, or accepting an pull request for? or am I barking up the wrong tree?

**Comment by ogrisel** [comment]
I have personally no strong objection against that suggestion.

**Comment by ygravrand** [comment]
I have no objection either!

**Comment by rgbkrk** [comment]
Same here, feel free to submit a PR.

**Comment by parnmatt** [comment]
Surprisingly it was just as simple as adding those two lines.

**Comment by rgbkrk** [comment]
Should I release this as 2.0 @ogrisel? That's what we have as the current dev setting, but I can't imagine this as an API change per se.

**Comment by ygravrand** [comment]
@parnmatt out of curiosity, when you say
> cloudpickle can pickle something I need that dill cannot

what use case were you referring to?

**Comment by ogrisel** [comment]
1.1 is fine for backward compatible changes I think. But this new API should be officially documented and tested before releasing.

**Comment by parnmatt** [comment]
@ygravrand I am working with SymPy. I am converting expressions into anonymous functions using `sympy.lamdify`, now both `dill` and `cloudpickle` can pickle lambdas, however `dill` kept throwing errors, e.g.,

> PicklingError: Can't pickle <class 'mpmath.ctx_mp_python.constant'>: it's not found as mpmath.ctx_mp_python.constant

Whereas `cloudpickle` handles it just fine, and allows me to calculate these functions and store them in files for later use.

**Comment by ogrisel** [comment]
@parnmatt you should report that specific issue to the dill developers with a minimalistic code snippet that reproduce the error (including import statements). I am sure the dill developers would love to get the opportunity to fix it.

**Comment by ygravrand** [comment]
@parnmatt thx for your answer, the dill error seems strange though. Dill developers may find it worth looking into it.

**Comment by parnmatt** [comment]
@ygravrand @ogrisel I have opened a ticket with `dill` to inform them of this. I hope I can be of some help to them.
