### ISSUE TITLE
cloudpickle extremely slow on pickling Dict[int, float]

### ISSUE THREAD

**Issue by basnijholt** [cloudpipe/cloudpickle#375]
In an attempt to fix (circumvent) https://github.com/cloudpipe/cloudpickle/issues/374 I found that `cloudpickle` is extremely slow on pickling large dictionaries with very simple datatypes (float and int):

```python
import pickle
import random
import cloudpickle

floats = {i: random.random() for i in range(30_000)}
np_floats64 = {i: np.float64(v) for i, v in floats.items()}

%timeit len(pickle.dumps(floats))
%timeit len(pickle.dumps(np_floats64))

%timeit len(cloudpickle.dumps(floats))
%timeit len(cloudpickle.dumps(np_floats64))
```
prints
```
1.3 ms ± 3.19 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
82.7 ms ± 1.26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
88.1 ms ± 335 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
519 ms ± 4.65 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Where `cloudpickle` is about a 60x slower than `pickle` for `float`s and 6x slower for `np.float64`s.

* https://github.com/cloudpipe/cloudpickle/issues/68 reports a similar issue but @pierreglaser mentions that the performance issues have been fixed [here](https://github.com/cloudpipe/cloudpickle/issues/68#issuecomment-501626240).
* a similar issue has been fixed for NumPy: https://github.com/cloudpipe/cloudpickle/issues/58
* I used version `cloudpickle` version 1.3.0 and Python 3.7.6

**Comment by ogrisel** [comment]
You should try running the same benchmark with Python 3.8: cloudpickle can use the C implementation of the Pickler class which should significantly help for this kind of workloads.

**Comment by ogrisel** [comment]
Here are the numbers on my machine with Python 3.8.2 and cloudpickle 1.4.1:

```
In [4]: %timeit len(pickle.dumps(floats))                                                                                                                                       
1.1 ms ± 61 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [5]: %timeit len(pickle.dumps(np_floats64))                                                                                                                                  
73.8 ms ± 4.87 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [6]: %timeit len(cloudpickle.dumps(floats))                                                                                                                                  
1.17 ms ± 74.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [7]: %timeit len(cloudpickle.dumps(np_floats64))                                                                                                                             
80.4 ms ± 904 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by ogrisel** [comment]
Closing as this was fixed a while ago and is just a matter of upgrading to a more recent version of Python.
