### ISSUE TITLE
uninitialized classmethod object

### ISSUE THREAD

**Issue by hyukim17** [cloudpipe/cloudpickle#40]
I have a very simple classmethod example that fails.

```
import cloudpickle
import pickle

class A(object):
  @classmethod
  def test(cls):
    pass


a = A()

res = cloudpickle.dumps(a)
new_obj = pickle.loads(res)

new_obj.__class__.test()
```

**Comment by rgbkrk** [comment]
Sure enough, that's definitely not working right in both Python2 and Python3.

**Comment by hyukim17** [comment]
I posted the same problem on the dill forums and they had a fix:

https://github.com/uqfoundation/dill/issues/124#issuecomment-132637923

It can be applied to cloudpickle as well.

For the record, I prefer using cloudpickle because it is better at handling globals and embedded namespaces.

**Comment by rgbkrk** [comment]
From that solution and what we have here, do you think there's a way to patch this on cloudpickle?

**Comment by hyukim17** [comment]
So I tried a couple test cases, and it fails in a way that dill doesn't -- I need to spend some time isolating the test case, but it runs into

```
File "/usr/lib/python2.7/pickle.py", line 244, in memoize
  assert id(obj) not in self.memo
AssertionError
```

when I naively applied the dill solution to cloudpickle.

**Comment by PureW** [comment]
Is this still being worked on or did the patch fix the test-case? Because I am experiencing the same problem: `assert id(obj) not in self.memo` with a fairly complex object that works fine with cloud.serialization.cloudpickle. 

I was hoping to be able to switch cloud.serialization.cloudpickle but it seems it is not on par yet.

**Comment by hyukim17** [comment]
For what it's worth, I have a hack solution to fix the `assert id(obj) not in self.memo` problem.
My belief is that essentially the pickling framework tries very hard not to memoize the same object twice. When that occurs, the framework assumes something went wrong and raises and assertion. This behavior also exists in Python's built-in pickling libraries. However, classmethods and staticmethods as they are handled in `cloudpickle` seem to often run into that assertion. My fix is to use the following:

```
if type(obj) not in [classmethod, staticmethod, type]:
  assert id(obj) not in self.memo
else:
  assert id(obj) not in self.memo or self.memo[id(obj)][1] is obj
```

I wanted to limit the hack to only certain types that I have problems with, in order to minimize potential side effects. This code runs the original code for most types. For `classmethod`, `staticmethod`, and `type` types, it either requires the memoization to never have happened, or if it has, the object must be the same (pointer-wise).

`dill` unfortunately handles recursive namespace pickling much worse than `cloudpickle` (it runs into infinite recursion issues), so I prefer using `cloudpickle` with the above hack.

**Comment by llllllllll** [comment]
This appears to have been fixed.
