### ISSUE TITLE
cloudpickle cannot pickle CompiledFunction (JAX)

### ISSUE THREAD

**Issue by KristianHolsheimer** [cloudpipe/cloudpickle#402]
Hi there,

I'm having issues pickling a function that's been JIT-compiled with JAX:

```python
import jax
import cloudpickle as pickle

@jax.jit
def func(x):
  return x * 13

# this attribute is the culprit
pickle.dumps(func._cpp_jitted_f)  # raises TypeError
```
> TypeError: cannot pickle 'jaxlib.xla_extension.jax_jit.CompiledFunction' object

I checked to see if `func._cpp_jitted_f` has `__reduce__` or `__getstate__`/`__setstate__` implemented:

```python
func._cpp_jitted_f.__reduce__()  # OK
```
> (<function copyreg._reconstructor(cls, base, state)>, (jaxlib.xla_extension.jax_jit.CompiledFunction, object, None))

This looks like a generic implementation.

The `__getstate__` and `__setstate__` are not implemented.
```python
func._cpp_jitted_f.__getstate__()     # raises AttributeError
func._cpp_jitted_f.__setstate__(...)  # raises AttributeError
```
I thought that would be alright as long as `__reduce__` is defined. Is that not correct?

By the way, as the name suggests `func._cpp_jitted_f` is defined in cpp ([here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/python/jax_jit.cc#L275)), not directly in python.

**I'd love to help out and send in a PR to fix this, but I don't know where to start. Any help would be much appreciated.**

### System information
OS: Ubuntu 20.04.1 LTS
Python: 3.8.5
pip freeze:
- `jax==0.2.6`
- `jaxlib==0.1.57`
- `cloudpickle==1.6.0`

**Comment by pierreglaser** [comment]
Hi,
Thanks for the report.

`cloudpickle` does not support (yet) pickling dynamically compiled/jitted python functions. Apart for jax, another example of dynamically compiled functions are functions defined in a cell that uses the `%%cython` in a `jupyter` notebook.

I have limited bandwidth to investigate it, but if you want to give it a shot I'm happy to review PRs. 
There are two ways of doing this that I can think of:
1. either serialize the jitted function
2. or serialize the original function and and a `jax.jit` call - in this case, the function will be re-jitted when loading the pickle.

1 is more efficient than 2, but 1 may or may *not* be possible depending on how much of the `jitted`-function is exposed at the `Python`-level.

**Comment by KristianHolsheimer** [comment]
Thanks so much for looking into this @pierreglaser 

This needs to be implemented on the JAX / XLA side. I'm planning to have a crack at it once I have some spare time.

Like your option 2. That feels cleaner somehow. I'll have a look at how to accomplish this.

I'll report back for any updates.

Cheers!

**Comment by KristianHolsheimer** [comment]
@pierreglaser I ended up implementing your suggestion [here](https://github.com/microsoft/coax/blob/main/coax/utils/_jit.py).

Thanks for pointing me in the right direction!

**Comment by zhisbug** [comment]
Hi, @KristianHolsheimer the link you posted in the previous reply is lost. 
Actually, I'm wondering how you eventually make the `CompiledFunction` pickled? Would appreciate your help as I am facing exactly the same issue!
