### ISSUE TITLE
curious if there are plans for a release

### ISSUE THREAD

**Issue by smacke** [cloudpipe/cloudpickle#433]
Hi,

Thanks to the maintainers for starting this project -- it's hard to overstate the impact that cloudpickle has had in filling in the gaps of Python's built-in pickling capabilities, and one only needs to look at the [pypistats for cloudpickle](https://pypistats.org/packages/cloudpickle) to see how important it has become in industry and other open source projects.

I was wondering if there are any plans for another release at some point -- I can see that there have been quite a lot of important developments since the last one, such as improved compatibility with Python 3.10. I don't mean to be pushy; as a maintainer of a few (far less impactful) open source projects myself, I know it's a thankless job. :) Just curious if there is a timeline in effect; no worries if not.

**Comment by pierreglaser** [comment]
Hi @smacke. We plan to release `cloudpickle` within the next couple weeks - before releasing, we typically check through tailored CI workflows that `cloudpickle` is backwards-compatible some widely used downstream libraries relying on cloudpickle, such as `ray`, `dask` and `joblib`. However, some of these workflows are broken, and need fixes (see #432 ). Once they are fixed, we can run the downstream tests, and once they pass, we will release `cloudpickle 2.0.0`.

**Comment by jrbourbeau** [comment]
Just checking in, since the `cloudpickle==2.0.0` release is out, can this issue be closed?

**Comment by pierreglaser** [comment]
It can be closed indeed, thanks @jrbourbeau!
