### ISSUE TITLE
Making "squash merging" default

### ISSUE THREAD

**Issue by jakirkham** [cloudpipe/cloudpickle#459]
After merging a PR recently, noticed other PRs here have been merged with "squash merging". Should we make this the default and/or only merge method?

No strong feelings personally. Just wondering how we can make it easier to do the expected merge behavior.

**Comment by jakirkham** [comment]
@ogrisel @pierreglaser ?

**Comment by pierreglaser** [comment]
I'm fine with squash merging being the default.

**Comment by jrbourbeau** [comment]
Whoops I think https://github.com/cloudpipe/cloudpickle/pull/450 might be to blame for the recent not-so-informative commits : ) FWIW we've standardized on squash merging over in Dask (as @jakirkham is well aware) and I think folks have been happy with that decision. GitHub allows you to explicitly disable various types of merging on PRs (see https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests) so all but "Squash and merge" could be disabled

**Comment by jakirkham** [comment]
Yep I dropped the ball there and clicked the merge button, which prompted this question 😅

**Comment by jakirkham** [comment]
Have gone ahead and made this change. Though please feel free to comment if you have thoughts here (this can always be changed again)
