### ISSUE TITLE
TypeError: cannot pickle 'ctranslate2.translator.Translator' object

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [cloudpipe/cloudpickle#483]
I have used the CTranslate2 inference within bentoML (https://github.com/OpenNMT/CTranslate2) with custom runner.

This library implements a custom runtime that applies many performance optimization techniques such as weights quantization, layers fusion, batch reordering, etc., to [accelerate and reduce the memory usage](https://github.com/OpenNMT/CTranslate2#benchmarks) of Transformer models on CPU and GPU.

But, when trying to save the model with cloudpickle, it results in the following error: TypeError: cannot pickle 'ctranslate2.translator.Translator' object.

To reproduce: please follow the following issue https://github.com/bentoml/BentoML/issues/3061

**Comment by pierreglaser** [comment]
from a quick glance at  [`CTranslate` ](https://github.com/OpenNMT/CTranslate2), `Translator` looks like an Extension type exposed via `pybind11`. Instances of extension types do not rely on the fallback `object.__reduce__` methods to pickle objects - there are only used for Python-only classes. To be able to pickle `Translator` classes, CTranslate2 must define an explicit serialization routine, like `__reduce__`.
