### ISSUE TITLE
pytest no longer bundles py

### ISSUE THREAD

**Issue by frenzymadness** [cloudpipe/cloudpickle#487]
py is kinda deprecated and pytest now bundles only a subset of it. It'd be best to stop depending on it. If it's not possible, dependency on py should be explicitly specified so the original package is installed.

https://github.com/cloudpipe/cloudpickle/blob/f5472e1a2eb4235e61b632b58367dede93dfb30c/tests/cloudpickle_test.py#L1472

**Comment by stanislavlevin** [comment]
https://docs.pytest.org/en/latest/changelog.html#pytest-7-2-0-2022-10-23:
> [#10396](https://github.com/pytest-dev/pytest/issues/10396): pytest no longer depends on the py library. pytest provides a vendored copy of py.error and py.path modules but will use the py library if it is installed. If you need other py.* modules, continue to install the deprecated py library separately, otherwise it can usually be removed as a dependency.

The affected test of `cloudpickle` relies on `py` package that previously was indirectly pulled into tests environment as pytest's dependency.

**Comment by frenzymadness** [comment]
And it seems that it has been there only for Python 2 compatibility which is not available in `py` since 2019.

**Comment by ogrisel** [comment]
Thanks, this was fixed in #494.

**Comment by ogrisel** [comment]
> And it seems that it has been there only for Python 2 compatibility which is not available in py since 2019.

I missed that. Feel free to open a follow-up PR to completely delete this test.
