### ISSUE TITLE
sdist is missing tox.ini

### ISSUE THREAD

**Issue by mtelka** [cloudpipe/cloudpickle#501]
The sdist package at PyPI is missing `tox.ini` file.  Please add the file to sdist to make downstream testing easier.   Thank you.

PS: Please add `dev-requirements.txt` to sdist too.

**Comment by ogrisel** [comment]
I switched the build to use `pyproject.toml` and `flit` but forgot to fix this. Please feel free to open a PR.

**Comment by mtelka** [comment]
The sdist for version 3.1.0 contains both `tox.ini` and `dev-requirements.txt`.

 Thank you.
