### ISSUE TITLE
Question: different Python versions

### ISSUE THREAD

**Issue by rhjohnstone** [cloudpipe/cloudpickle#505]
This is not really an issue, just a question.

The docs say:
> Cloudpickle can only be used to send objects between the exact same version of Python.

How exact is exact? When I look at `sys.version_info`, I see
```
sys.version_info(major=3, minor=9, micro=16, releaselevel='final', serial=0)
```
Do all of these fields need to match, or is up to minor, or micro, enough?

**Comment by HyukjinKwon** [comment]
Yes, they all have to be same. It's the limitation inherited from Python itself - even minor versions have some differences in pickled results.

**Comment by rhjohnstone** [comment]
Thank you @HyukjinKwon ! 🙏
