### ISSUE TITLE
Feature request: type inference without loading full byte stream

### ISSUE THREAD

**Issue by amalizzio** [cloudpipe/cloudpickle#539]
I have a large number of `cloudpickle` byte streams, and rather than pack them with metadata on top, I would like to be able to infer the object classes:

Simplified example:

```python
>>> d = {'a':1,'b':2'}
>>> b = cloudpickle.dumps(d)
>>> things.append(b)
... # later
>>> for thing in things[start:stop]:
...    typ = cloudpickle.inferType(thing) # some name like this
...    if typ==dict: # should support an arbitrary type
...        yield thing
```

Assuming the byte streams can be arbitrarily large, if this information can be packed at the front of the byte stream, it would be a low-cost operation not requiring full data load.

The quick-n-dirty way would be to just store `__class__.__name__`, or the `__repr__()` return, however I would like to perform exact type comparisons, so you need a way would be to load the type classes' module, and yield an instance of the type directly such that comparison operations can be made.

Is this a clear ask and if so, is it feasible?

**Comment by ogrisel** [comment]
cloudpickle is build on top of the regular pickle module of the standard library and as far as I know there is not standard way to do this without loading the pickle file first. So I think this is out of scope for this library. Storing external metadata is probably the way to go instead.
