### ISSUE TITLE
Cannot pickle Ellipsis objects

### ISSUE THREAD

**Issue by jakirkham** [cloudpipe/cloudpickle#54]
Appears that I cannot pickle an `Ellipsis` object, but I can pickle `slice`s. It would be nice to have support for pickling `Ellipsis`. FWIW, this is solved by `dill`.

    >>> import cloudpickle
    >>> cloudpickle.dumps(Ellipsis)
        ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-2-cc84d30bf9cd> in <module>()
    ----> 1 cloudpickle.dumps(Ellipsis)
    
    /zopt/conda/envs/nanshenv/lib/python2.7/site-packages/cloudpickle/cloudpickle.pyc in dumps(obj, protocol)
        600 
        601     cp = CloudPickler(file,protocol)
    --> 602     cp.dump(obj)
        603 
        604     return file.getvalue()
    
    /zopt/conda/envs/nanshenv/lib/python2.7/site-packages/cloudpickle/cloudpickle.pyc in dump(self, obj)
        105         self.inject_addons()
        106         try:
    --> 107             return Pickler.dump(self, obj)
        108         except RuntimeError as e:
        109             if 'recursion' in e.args[0]:
    
    /zopt/conda/envs/nanshenv/lib/python2.7/pickle.pyc in dump(self, obj)
        222         if self.proto >= 2:
        223             self.write(PROTO + chr(self.proto))
    --> 224         self.save(obj)
        225         self.write(STOP)
        226 
    
    /zopt/conda/envs/nanshenv/lib/python2.7/pickle.pyc in save(self, obj)
        304             reduce = getattr(obj, "__reduce_ex__", None)
        305             if reduce:
    --> 306                 rv = reduce(self.proto)
        307             else:
        308                 reduce = getattr(obj, "__reduce__", None)
    
    TypeError: can't pickle ellipsis objects

**Comment by mrocklin** [comment]
This is being fixed in https://github.com/cloudpipe/cloudpickle/pull/52

**Comment by jakirkham** [comment]
Thanks for the heads-up, @mrocklin.

**Comment by jakirkham** [comment]
Fixed by https://github.com/cloudpipe/cloudpickle/pull/52
