### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by mrocklin** [cloudpipe/cloudpickle#55]
I would love to see a release of cloudpickle next week.  What is the procedure for this?

**Comment by rgbkrk** [comment]
I agree, we need to make a release. We've let this sit by on the side for too long.

The verdict was that we were going to bump the minor version for this release, is that correct?

**Comment by rgbkrk** [comment]
How do you tend to automate your releases for dask and other projects @mrocklin? Since we're pure python, we never wrote dedicated release steps. I'm happy to ship as is, though I'd love to hear if/what you'd like to see beyond a sdist upload.

**Comment by mrocklin** [comment]
That's all I do really.  https://github.com/dask/dask/blob/master/docs/release-procedure.md

**Comment by mrocklin** [comment]
Wheel people get upset with this though, we should probably release a universal wheel

**Comment by mrocklin** [comment]
https://github.com/dask/dask/issues/662#issuecomment-169146954

**Comment by mrocklin** [comment]
I believe that `cloudpickle` is in the anaconda packages and so conda packages should be built and released for it automatically after a day or two.

**Comment by mrocklin** [comment]
Thought I'd bump this.  Any thoughts @rgbkrk or @ogrisel ?  Who usually handles this?

**Comment by rgbkrk** [comment]
Running the `v0.2.0` release now, updating the changelog. I did it both of these last times.

**Comment by rgbkrk** [comment]
Shipped as `v0.2.1`, including universal wheels.
