### ISSUE TITLE
(doc) PiCloud links in comments are dead

### ISSUE THREAD

**Issue by pyhedgehog** [cloudpipe/cloudpickle#60]
https://github.com/cloudpipe/cloudpickle/blob/62027de3b76552fc2294e04b2e89c186b9270238/cloudpickle/cloudpickle.py#L12

**Comment by rgbkrk** [comment]
Very true. It should probably be changed to just say "PiCloud Inc."

**Comment by pyhedgehog** [comment]
Also possibly some disambiguation needed (there are something likely named for raspberry-pi).
Also link to archive can be referenced: http://web.archive.org/web/20140717073517/http://www.picloud.com/
Or archive of death announcement: http://web.archive.org/web/20140721022102/http://blog.picloud.com/2013/11/17/picloud-has-joined-dropbox/

**Comment by rgbkrk** [comment]
Oooh, archive is a really good idea.
