### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by rgbkrk** [cloudpipe/cloudpickle#70]
Hey @ogrisel, @mrocklin, @pitrou!

We should make a release. I've made the last few, I'd love to have someone else take the reigns on shipping. Since I'm no longer using this package directly, I don't have much vested interest in getting this shipped (other than as a user of dask and pyspark).

@pitrou - what is your username on PyPI?

**Comment by pitrou** [comment]
My username on PyPI is `antoine`.

**Comment by rgbkrk** [comment]
Added you, thank you.

**Comment by pitrou** [comment]
Are the steps required to make a release describe somewhere? A particular "setup.py" invocation perhaps?

**Comment by mrocklin** [comment]
@rgbkrk is this just the following?

```
git clean -xfd
python setup.py sdist bdist_wheel --universal
twine upload dist/*
```

**Comment by rgbkrk** [comment]
Seems about right

**Comment by ogrisel** [comment]
+1

**Comment by pitrou** [comment]
Also bump the version number somewhere?

**Comment by ogrisel** [comment]
Yes and push a new tag to github as well.

**Comment by mrocklin** [comment]
I'll eventually do this once it becomes necessary for Dask.  The Tornado
release will presumably force this at some point.

**Comment by pitrou** [comment]
Perhaps #71 should be solved before making a new release.

**Comment by mrocklin** [comment]
I plan to issue a new release of cloudpickle on PyPI and conda-forge tomorrow if no one raises any objections before then.

**Comment by mrocklin** [comment]
I've added Python 3.6 to the travis testing matrix, released version 0.2.2 to PyPI, and submitted a PR to the conda-forge feedstock.  However, I don't have write permissions to the conda-forge repository so one of the current maintainers will have to merge https://github.com/conda-forge/cloudpickle-feedstock/pull/6

**Comment by rgbkrk** [comment]
Great, thanks Matthew.

**Comment by Peque** [comment]
Are there any blocking issues preventing a new release? Otherwise I would be interested in a new version that includes @ssanderson changes and the `__transient__` support removal. :blush:

If you are going to increase the major version due to the `__transient__` change maybe it would be a good moment to officially [drop Python 2.6 and 3.3 support](https://github.com/cloudpipe/cloudpickle/issues/98)?

**Comment by hugovk** [comment]
This can be closed now.

Python 2.6 and 3.3 were dropped in https://github.com/cloudpipe/cloudpickle/pull/122 https://github.com/cloudpipe/cloudpickle/pull/125.

Cloudpickle v0.4.1 was released two days ago: https://github.com/cloudpipe/cloudpickle/releases

**Comment by rgbkrk** [comment]
Thanks for all the issue stewardship @hugovk! I'm going to add you to the repo to make it easier for you to close issues as part of triage.
