### ISSUE TITLE
Supported Python versions

### ISSUE THREAD

**Issue by pitrou** [cloudpipe/cloudpickle#98]
cloudpickle currently tries to support Python 2.6 and 3.3. Does anyone still need support for those older Python versions, or can we drop them?

**Comment by pitrou** [comment]
@ogrisel @rgbkrk @mrocklin @jakirkham @llllllllll

**Comment by mrocklin** [comment]
I'm fine with dropping these.

**Comment by robertnishihara** [comment]
Probably ok to drop them.

**Comment by mrocklin** [comment]
By the way, everyone say hi to @robertnishihara , who works on [Ray](http://ray.readthedocs.io/en/latest/) a newish distributed computing system for Python that also uses cloudpickle.  We should probably ping him on other issues like this one in the future :)

**Comment by robertnishihara** [comment]
Thanks @mrocklin, hi everyone!

**Comment by pitrou** [comment]
Hi @robertnishihara !

**Comment by jakirkham** [comment]
FWIW I find [this list]( https://docs.python.org/devguide/#status-of-python-branches ) of supported Python versions with their EOLs handy.

👍 to dropping Python 2.6 and 3.3. FWIW pip has already dropped 2.6. As for 3.3 its EOL is later this year, I can't see any good reason to hang on to it.

**Comment by rgbkrk** [comment]
At the time I think we kept 2.6 because we wanted parity with what pyspark was supporting (so they could vendor / use this directly). PySpark has since dropped support for < 2.7 IIRC

/cc @holdenk

**Comment by jakirkham** [comment]
Looks like PySpark doesn't support Python 3.3 at least since v2.1.0.

ref: https://github.com/apache/spark/blob/v2.1.0/python/setup.py#L207-L210

**Comment by pitrou** [comment]
So should we support 2.6 and 3.3 in the next release still, or drop support right now?

**Comment by rgbkrk** [comment]
I think dropping support now is just fine. 2.7+ and 3.4+ or bust.

**Comment by hugovk** [comment]
This can be closed now, 2.6 and 3.3 were dropped in https://github.com/cloudpipe/cloudpickle/pull/122 https://github.com/cloudpipe/cloudpickle/pull/125.
